name: linter-ruff

on: pull_request

defaults:
    run:
        shell: bash

jobs:
    ruff-lint:
        uses: SwooshyCueb/irods_reusable_github_workflows/.github/workflows/linter-irods-ruff.yml@36.m
